### ISSUE TITLE
Initial set up

### ISSUE THREAD

**Issue by ZiyueChloeZhang** [jack007lyz/easy-drive#5]
Set up your project with React. You MUST start your project with the create-react-app boilerplate code. Once the boilerplate code has been set up, do an initial push to your project repo that you have set up with your group. It could take some git gymnastics to make it work. Make sure your README does not get overwritten! (Or copy it over to a new repo)

**Comment by kaiqianyyang** [comment]
- **Done** 
  - [x] npx create-react-app easy-drive
  - [x] npm install redux
  - [x] npm install react-redux
- **Todo**
  - [ ] Wait to be tested by other team members.
    - Test ways
      - git checkout Initial-code-set-up
      - npm start
    OR
      - git checkout Initial-code-set-up
      - npm install
      - npm install redux
      - npm install react-redux
      - npm start

**Comment by jack007lyz** [comment]
Works for me.

**Comment by ZiyueChloeZhang** [comment]
Thank you Cathy! It works for me too.
